import { Image } from "react-grid-gallery";

export interface CustomImage extends Image {
  original: string;
}

export const images: CustomImage[] = [
  {
    src: "/images/internal/IMG_0234.JPG",
    original: "//images/internal/IMG_0234.JPG",
    width: 850,
    height: 445,
    caption: "Master bathroom-1",
  },
  {
    src: "/images/internal/IMG_0235.JPG",
    original: "//images/internal/IMG_0235.JPG",
    width: 792,
    height: 445,
    caption: "Master bathroom-2",
  },
  {
    src: "/images/internal/IMG_0238.JPG",
    original: "//images/internal/IMG_0238.JPG",
    width: 900,
    height: 445,
    caption: "Master bathroom-3",
  },
  {
    src: "/images/internal/IMG_0236.JPG",
    original: "//images/internal/IMG_0236.JPG",
    width: 792,
    height: 445,
    caption: "Master bedroom",
  },
  {
    src: "/images/internal/IMG_0237.JPG",
    original: "//images/internal/IMG_0237.JPG",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/IMG_0239.JPG",
    original: "//images/internal/IMG_0239.JPG",
    width: 792,
    height: 445,
    caption: "Gym Room",
  },
  {
    src: "/images/internal/IMG_0240.JPG",
    original: "//images/internal/IMG_0240.JPG",
    width: 900,
    height: 445,
    caption: "Second floor",
  },
  {
    src: "/images/internal/IMG_0241.JPG",
    original: "//images/internal/IMG_0241.JPG",
    width: 792,
    height: 445,
    caption: "Bedroom 2",
  },
  {
    src: "/images/internal/IMG_0242.JPG",
    original: "//images/internal/IMG_0242.JPG",
    width: 792,
    height: 445,
    caption: "Living Room-2",
  },
  {
    src: "/images/internal/IMG_0243.JPG",
    original: "//images/internal/IMG_0243.JPG",
    width: 792,
    height: 445,
    caption: "Living Room-3",
  },
  {
    src: "/images/internal/IMG_0244.JPG",
    original: "//images/internal/IMG_0244.JPG",
    width: 920,
    height: 445,
    caption: "Living Room-4",
  },
  {
    src: "/images/internal/IMG_0245.JPG",
    original: "//images/internal/IMG_0245.JPG",
    width: 850,
    height: 445,
    caption: "Kitchen Room",
  },
  {
    src: "/images/internal/IMG_0246.JPG",
    original: "//images/internal/IMG_0246.JPG",
    width: 792,
    height: 445,
    caption: "Second Floor-2",
  },
  {
    src: "/images/internal/IMG_0247.JPG",
    original: "//images/internal/IMG_0247.JPG",
    width: 890,
    height: 445,
    caption: "Bedroom 2",
  },
  {
    src: "/images/internal/IMG_0248.JPG",
    original: "//images/internal/IMG_0248.JPG",
    width: 960,
    height: 445,
    caption: "Bedroom 1",
  },
  {
    src: "/images/external/IMG_0249.JPG",
    original: "//images/external/IMG_0249.JPG",
    width: 792,
    height: 445,
    caption: "Front side",
  },
  {
    src: "/images/external/IMG_0250.JPG",
    original: "//images/external/IMG_0250.JPG",
    width: 792,
    height: 445,
    caption: "Front side",
  },
  {
    src: "/images/external/IMG_0251.JPG",
    original: "//images/external/IMG_0251.JPG",
    width: 950,
    height: 445,
    caption: "Back side",
  },
  {
    src: "/images/external/IMG_0252.JPG",
    original: "//images/external/IMG_0252.JPG",
    width: 850,
    height: 500,
    caption: "Floor Plan 1st floor",
  },
];
