import { Image } from "react-grid-gallery";

export interface CustomImage extends Image {
  original: string;
}

export const images: CustomImage[] = [
  {
    src: "/images/internal/p1.jpg",
    original: "//images/internal/p1.jpg",
    width: 850,
    height: 445,
    caption: "Master bathroom",
  },
  {
    src: "/images/internal/p2.jpg",
    original: "//images/internal/p2.jpg",
    width: 792,
    height: 445,
    caption: "Master bathroom",
  },
  {
    src: "/images/internal/p3.jpg",
    original: "//images/internal/p3.jpg",
    width: 900,
    height: 445,
    caption: "Master bedroom",
  },
  {
    src: "/images/internal/p4.jpg",
    original: "//images/internal/p4.jpg",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p5.jpg",
    original: "//images/internal/p5.jpg",
    width: 792,
    height: 445,
    caption: "Master bathroom",
  },
  {
    src: "/images/internal/p6.jpg",
    original: "//images/internal/p6.jpg",
    width: 792,
    height: 445,
    caption: "Gym Room",
  },
  {
    src: "/images/internal/p7.jpg",
    original: "//images/internal/p7.jpg",
    width: 900,
    height: 445,
    caption: "Second floor",
  },
  {
    src: "/images/internal/p8.jpg",
    original: "//images/internal/p8.jpg",
    width: 792,
    height: 445,
    caption: "Bedroom 2",
  },
  {
    src: "/images/internal/p9.jpg",
    original: "//images/internal/p9.jpg",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p10.jpg",
    original: "//images/internal/p10.jpg",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p11.jpg",
    original: "//images/internal/p11.jpg",
    width: 920,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p12.jpg",
    original: "//images/internal/p12.jpg",
    width: 850,
    height: 445,
    caption: "Kitchen Room",
  },
  {
    src: "/images/internal/p13.jpg",
    original: "//images/internal/p13.jpg",
    width: 792,
    height: 445,
    caption: "Second Floor",
  },
  {
    src: "/images/internal/p14.jpg",
    original: "//images/internal/p14.jpg",
    width: 890,
    height: 445,
    caption: "Bedroom 2",
  },
  {
    src: "/images/internal/p15.jpg",
    original: "//images/internal/p15.jpg",
    width: 960,
    height: 445,
    caption: "Bedroom 1",
  },
  {
    src: "/images/external/outside-1.jpg",
    original: "//images/external/outside-1.jpg",
    width: 792,
    height: 445,
    caption: "outside view",
  },
  {
    src: "/images/external/outside-2.jpg",
    original: "//images/external/outside-2.jpg",
    width: 792,
    height: 445,
    caption: "outside view",
  },
  {
    src: "/images/external/outside-3.jpg",
    original: "//images/external/outside-3.jpg",
    width: 950,
    height: 445,
    caption: "outside view",
  },
  {
    src: "/images/external/outside-4.jpg",
    original: "//images/external/outside-4.jpg",
    width: 850,
    height: 500,
    caption: "outside view",
  },
  {
    src: "/images/external/pool-view.jpg",
    original: "//images/external/pool-view.jpg",
    width: 850,
    height: 500,
    caption: "Pool View",
  },
  {
    src: "/images/external/floorplan-1st-floor.jpg",
    original: "//images/external/floorplan-1st-floor.jpg",
    width: 750,
    height: 500,
    caption: "Floor plan (1st floor)",
  },
  {
    src: "/images/external/floorplan-2nd-floor.jpg",
    original: "//images/external/floorplan-2nd-floor.jpg",
    width: 750,
    height: 500,
    caption: "Floor plan (2nd floor)",
  },
];
