import { Image } from "react-grid-gallery";

export interface CustomImage extends Image {
  original: string;
}

export const images: CustomImage[] = [
  {
    src: "/images/internal/p1.jpg",
    original: "//images/internal/p1.jpg",
    width: 850,
    height: 445,
    caption: "Master bathroom",
  },
  {
    src: "/images/internal/p2.jpg",
    original: "//images/internal/p2.jpg",
    width: 792,
    height: 445,
    caption: "Master bathroom",
  },
  {
    src: "/images/internal/p3.jpg",
    original: "//images/internal/p3.jpg",
    width: 900,
    height: 445,
    caption: "Master bedroom",
  },
  {
    src: "/images/internal/p4.jpg",
    original: "//images/internal/p4.jpg",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p5.jpg",
    original: "//images/internal/p5.jpg",
    width: 792,
    height: 445,
    caption: "Master bathroom",
  },
  {
    src: "/images/internal/p6.jpg",
    original: "//images/internal/p6.jpg",
    width: 792,
    height: 445,
    caption: "Gym Room",
  },
  {
    src: "/images/internal/p7.jpg",
    original: "//images/internal/p7.jpg",
    width: 900,
    height: 445,
    caption: "Second floor",
  },
  {
    src: "/images/internal/p8.jpg",
    original: "//images/internal/p8.jpg",
    width: 792,
    height: 445,
    caption: "Bedroom 2",
  },
  {
    src: "/images/internal/p9.jpg",
    original: "//images/internal/p9.jpg",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p10.jpg",
    original: "//images/internal/p10.jpg",
    width: 792,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p11.jpg",
    original: "//images/internal/p11.jpg",
    width: 920,
    height: 445,
    caption: "Living Room",
  },
  {
    src: "/images/internal/p12.jpg",
    original: "//images/internal/p12.jpg",
    width: 850,
    height: 445,
    caption: "Kitchen Room",
  },
  {
    src: "/images/internal/p13.jpg",
    original: "//images/internal/p13.jpg",
    width: 792,
    height: 445,
    caption: "Second Floor",
  },
  {
    src: "/images/internal/p14.jpg",
    original: "//images/internal/p14.jpg",
    width: 890,
    height: 445,
    caption: "Bedroom 2",
  },
  {
    src: "/images/internal/p15.jpg",
    original: "//images/internal/p15.jpg",
    width: 960,
    height: 445,
    caption: "Bedroom 1",
  },
  {
    src: "/images/external/IMG_0249.JPG",
    original: "//images/external/IMG_0249.JPG",
    width: 792,
    height: 445,
    caption: "Front side",
  },
  {
    src: "/images/external/IMG_0250.JPG",
    original: "//images/external/IMG_0250.JPG",
    width: 792,
    height: 445,
    caption: "Front side",
  },
  {
    src: "/images/external/IMG_0251.JPG",
    original: "//images/external/IMG_0251.JPG",
    width: 950,
    height: 445,
    caption: "Back side",
  },
  {
    src: "/images/external/IMG_0252.JPG",
    original: "//images/external/IMG_0252.JPG",
    width: 850,
    height: 500,
    caption: "Floor Plan 1st floor",
  },
];
